services:
  influxdb:
    container_name: influxDB
    image: influxdb:2.6.1
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=kohaku
      - DOCKER_INFLUXDB_INIT_PASSWORD=kmanjing
      - DOCKER_INFLUXDB_INIT_ORG=sgh
      - DOCKER_INFLUXDB_INIT_BUCKET=aeroponics
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
 